# isa2.ml's [Spec] is a verbatim copy of the body of the functor [Make] (see the comment above
# [Spec]). Without -v write=1: check that the copy is verbatim, print a one-line OCaml module on
# success, fail on a difference. With -v write=1: print isa2.ml with the copy brought up to date.
/^  \(\* BEGIN body of Make \*\)$/ { in_body = 1; print_line(); next }
/^  \(\* END body of Make \*\)$/ { in_body = 0; print_line(); next }
/^  \(\* BEGIN copy of Make's body \*\)$/ {
  in_copy = 1; print_line()
  if (write) for (i = 1; i <= n_body; i++) print body[i]
  next
}
/^  \(\* END copy of Make's body \*\)$/ { in_copy = 0; print_line(); next }
in_body { body[++n_body] = $0 }
in_copy { copy[++n_copy] = $0; if (write) next }
{ print_line() }
function print_line() { if (write) print }
END {
  if (write) exit 0
  if (n_body == 0) { print FILENAME ": no body of Make between the markers" > "/dev/stderr"; exit 1 }
  for (i = 1; i <= n_body || i <= n_copy; i++)
    if (body[i] != copy[i]) {
      printf "%s: Spec's copy of Make's body differs at its line %d; run ./specialise.sh\n", FILENAME, i > "/dev/stderr"
      exit 1
    }
  print "(* Generated by specialise.awk: isa2.ml's Spec is a verbatim copy of Make's body. *)"
}
