(* The programme store of the UART miter (uart-miter/, README.md section 7) as a Verilog ROM:
   thread 0 runs the compiler's UART transmitter on pin 0 taking [n] bytes from the host
   (Programmes.uart_from_host, the programme of property (d)); threads 1-3 halt.
   Usage: uart_rom.exe N [stretch] > FILE     stretch: the compiler's fault injector, data bit 3
   of the first byte 3 slots longer (the planted bug of d-planted) *)
let () =
  let n = int_of_string Sys.argv.(1) in
  let stretch = if Array.length Sys.argv > 2 && Sys.argv.(2) = "stretch" then Some (3, 3) else None in
  let u = Programmes.uart_from_host ?stretch ~bit_slots:5 n in
  let store = Programmes.store_of [| u; Programmes.idle; Programmes.idle; Programmes.idle |] in
  (* HALT translates to a jump to itself, so the default word is "jmp pc" *)
  (* beyond a base programme's length (Isa.prog_len) the store holds 0, a NOP *)
  let halt a = if a land 0xFF < Isa.prog_len then Isa2.jmp (a land 0xFF) else 0 in
  Printf.printf "// generated by prototypes/formal/uart_rom.exe %s; do not edit\n"
    (String.concat " " (List.tl (Array.to_list Sys.argv)));
  print_string "module uart_rom (input [9:0] addr, output reg [15:0] data);\n  always @(*)\n    case (addr)\n";
  Array.iteri (fun a w -> if w <> halt a then Printf.printf "      10'd%d: data = 16'h%04x;  // %s\n" a w (Isa2.disasm w)) store;
  Printf.printf "      default: data = addr[7:0] < %d ? {8'h%02x, addr[7:0]} : 16'h0000;  // halt (jmp to itself), or nop\n    endcase\nendmodule\n"
    Isa.prog_len (Isa2.jmp 0 lsr 8)
