# Writes src/config.json (both macros) and variants/config-512x16-only.json from tt/src/config.json.
# Run from prototypes/chip-top/sram-macro: uv run --no-project python scripts/mkconfig.py
import json, re, sys
tmpl = open('../../../tt/src/config.json').read()
SRAM = 'pdk_dir::libs.ref/sg13cmos5l_sram'
def macro(name, inst, loc):
    return {
        "instances": {inst: {"location": loc, "orientation": "FS"}},
        "gds": [f"{SRAM}/gds/{name}.gds"],
        "lef": [f"{SRAM}/lef/{name}.lef"],
        "lib": {
            "*_typ_*":  [f"{SRAM}/lib/{name}_typ_1p20V_25C.lib"],
            "*_fast_*": [f"{SRAM}/lib/{name}_fast_1p32V_m55C.lib"],
            "*_slow_*": [f"{SRAM}/lib/{name}_slow_1p08V_125C.lib"],
        },
        "nl": [f"dir::{name}.v"],
        "spice": [f"{SRAM}/cdl/{name}.cdl"],
    }
def block(both):
    macros = {"RM_IHPSG13_1P_512x16_c2_bm_bist": macro("RM_IHPSG13_1P_512x16_c2_bm_bist", "sram512", [12, 40])}
    conns = ["sram512 VPWR VGND VDD! VSS!", "sram512 VPWR VGND VDDARRAY! VSS!"]
    if both:
        macros["RM_IHPSG13_1P_1024x8_c2_bm_bist"] = macro("RM_IHPSG13_1P_1024x8_c2_bm_bist", "sram1024", [326.72, 40])
        conns += ["sram1024 VPWR VGND VDD! VSS!", "sram1024 VPWR VGND VDDARRAY! VSS!"]
    lines = []
    def c(s): lines.append('  "//": ' + json.dumps(s) + ',')
    def kv(k, v): lines.append('  ' + json.dumps(k) + ': ' + json.dumps(v, indent=2).replace('\n', '\n  ') + ',')
    lines.append('')
    c("================= SRAM macros: prototypes/chip-top/sram-macro/README.md =================")
    c("Recipe: thomasgilbert481/tt_um_loom (Apache-2.0), src/config.json and docs/tt_cmos5l_facts.md")
    c("section 11. Paths use pdk_dir::, which LibreLane expands to $PDK_ROOT/ihp-sg13cmos5l.")
    c("MACROS: instance keys are the flattened instance paths (here top-level: sram512, sram1024).")
    c("FS mirrors about X: the signal pins (108 and 70, all at LEF y 0..0.26) face the rows above.")
    c("x positions put the macros' Metal4 power columns under the stripe grid below:")
    c("512x16 at x 12 (stripes at macro-local 17.24 + 67.44 k), 1024x8 at x 326.72 = 12 + 314.72")
    c("(stripes at macro-local 39.72 and 107.16). Any other x needs FP_PDN_VOFFSET recomputed;")
    c("src/pdn_cfg.tcl fails the PDN step if a stripe over a macro leaves its same-net columns.")
    c("lib keys name the process corner: the cmos5l STA corners are nom_typ_1p20V_25C,")
    c("nom_fast_1p32V_m40C and nom_slow_1p08V_125C; the macro's fast lib is characterised at -55 C.")
    kv("MACROS", macros)
    c("Both macro supplies (periphery VDD! and array VDDARRAY!) to VPWR; Tiny Tapeout has one supply.")
    kv("PDN_MACRO_CONNECTIONS", conns)
    c("LibreLane 3.1.0.dev3's pdn_cfg.tcl with the macro grid replaced by tt_um_loom's wrapper:")
    c("full-height Metal4 stripes through the macros' Metal4 power columns, checked.")
    kv("PDN_CFG", "dir::pdn_cfg.tcl")
    kv("MAGIC_MACRO_STD_CELL_SOURCE", "PDK")
    c("Magic's cmos5l DRC deck lacks the SRAM exceptions; the precheck's KLayout deck is the sign-off.")
    kv("ERROR_ON_MAGIC_DRC", False)
    c("The POWER stripes cross the Metal4 OBS between VDD! and VDDARRAY! columns (no real metal there).")
    kv("ERROR_ON_ILLEGAL_OVERLAPS", False)
    c("Extract the macros as abstract cells for LVS.")
    kv("MAGIC_EXT_ABSTRACT_CELLS", ["RM_IHPSG13_.*"])
    if not both:
        kv("VERILOG_DEFINES", ["SRAM_PROBE_NO_1024X8"])
    c("Stripe grid (tt_um_loom): pitch 6 x 11.24 (macro column pitch), POWER-GROUND 5.62, offset puts")
    c("the first POWER stripe at x 29.24. VWIDTH stays at the template's 2.1.")
    kv("FP_PDN_VSPACING", 3.52)
    kv("FP_PDN_VOFFSET", 26.36)
    c("======================= end SRAM macros =======================")
    lines.append('')
    return '\n'.join(lines) + '\n'
for both, out in [(True, 'src/config.json'), (False, 'variants/config-512x16-only.json')]:
    t = tmpl.replace('  "CLOCK_PORT": "clk",\n', '  "CLOCK_PORT": "clk",\n' + block(both), 1)
    t = t.replace('"FP_PDN_VPITCH": 50.0', '"FP_PDN_VPITCH": 67.44', 1)
    t = t.replace('  "//": "DO NOT EDIT THIS FILE before reading', '  "//": "tt/src/config.json (ttihp-verilog-template, cmos5l) plus the SRAM block and FP_PDN_VPITCH/VSPACING/VOFFSET.",\n  "//": "DO NOT EDIT THIS FILE before reading', 1)
    json.loads(t)
    open(out, 'w').write(t)
    print(out, 'ok')
