// Generated by ecppll (Project Trellis) with
//   ecppll --module pll_60_48 --clkin_name clk25 --clkin 25 --clkout0_name clk60 --clkout0 60
//          --clkout1_name clk48 --clkout1 48 --reset
// and then edited by hand, because ecppll picked a 600 MHz VCO on which 48 MHz is not reachable
// (it produced 50 MHz). Hand-picked: PFD 25/5 = 5 MHz, feedback CLKOP 60 MHz x 12,
// VCO = 60 x 8 = 480 MHz (legal range 400-800), CLKOP = 480/8 = 60 MHz, CLKOS = 480/10 = 48 MHz.
// CPHASE = DIV/2 - 1 as ecppll does for zero phase. nextpnr recomputes the output
// frequencies from these parameters, so the timing report checks the arithmetic.
// diamond 3.7 accepts this PLL
// diamond 3.8-3.9 is untested
// diamond 3.10 or higher is likely to abort with error about unable to use feedback signal
// cause of this could be from wrong CPHASE/FPHASE parameters
module pll_60_48
(
    input reset, // 0:inactive, 1:reset
    input clk25, // 25 MHz, 0 deg
    output clk60, // 60 MHz, 0 deg
    output clk48, // 48 MHz
    output locked
);
(* FREQUENCY_PIN_CLKI="25" *)
(* FREQUENCY_PIN_CLKOP="60" *)
(* FREQUENCY_PIN_CLKOS="48" *)
(* ICP_CURRENT="12" *) (* LPF_RESISTOR="8" *) (* MFG_ENABLE_FILTEROPAMP="1" *) (* MFG_GMCREF_SEL="2" *)
EHXPLLL #(
        .PLLRST_ENA("ENABLED"),
        .INTFB_WAKE("DISABLED"),
        .STDBY_ENABLE("DISABLED"),
        .DPHASE_SOURCE("DISABLED"),
        .OUTDIVIDER_MUXA("DIVA"),
        .OUTDIVIDER_MUXB("DIVB"),
        .OUTDIVIDER_MUXC("DIVC"),
        .OUTDIVIDER_MUXD("DIVD"),
        .CLKI_DIV(5),
        .CLKOP_ENABLE("ENABLED"),
        .CLKOP_DIV(8),
        .CLKOP_CPHASE(3),
        .CLKOP_FPHASE(0),
        .CLKOS_ENABLE("ENABLED"),
        .CLKOS_DIV(10),
        .CLKOS_CPHASE(4),
        .CLKOS_FPHASE(0),
        .FEEDBK_PATH("CLKOP"),
        .CLKFB_DIV(12)
    ) pll_i (
        .RST(reset),
        .STDBY(1'b0),
        .CLKI(clk25),
        .CLKOP(clk60),
        .CLKOS(clk48),
        .CLKOS2(),
        .CLKOS3(),
        .CLKFB(clk60),
        .CLKINTFB(),
        .PHASESEL0(1'b0),
        .PHASESEL1(1'b0),
        .PHASEDIR(1'b1),
        .PHASESTEP(1'b1),
        .PHASELOADREG(1'b1),
        .PLLWAKESYNC(1'b0),
        .ENCLKOP(1'b0),
        .LOCK(locked),
        .ENCLKOS(),
        .ENCLKOS2(),
        .ENCLKOS3(),
        .INTLOCK(),
        .REFCLK()
	);
endmodule
