# Worst-corner lifetime of the level-shifted thin cell for every (data-0 level VLO, bar level,
# sense time), for two WBL scenarios:
#   opp:  WBL sits at the opposite data level for the whole hold (a column written with 1s all the
#         time; the worst case for a stored 0);
#   park: WBL returns to VLO between writes (an idle column). The stored 1 sees WBL = VLO in both.
# Also "tracking": the bar chosen per corner from the simulated levels (0 .. 0.3 V), an upper bound
# for a bar generated by a replica that tracks the process corner and temperature.
# Uses life.py's thresholds and interpolation. Output: results/matrix.txt.
import math, os, sys
sys.argv = ["life.py", "x"]           # life.py parses argv at import; neutralise it
here = os.path.dirname(os.path.abspath(__file__))
src = open(os.path.join(here, "life.py")).read().split("print(f\"read thresholds")[0]
ns = {}
exec(src.replace("readf, holdfs = args[0], args[1:]", "readf, holdfs = None, []").replace(
    "for line in open(readf):", "for line in []:"), ns)
R = os.path.join(here, "results")
BARS = ["0", "0.05", "0.1", "0.15", "0.2", "0.3"]
VLOS = ["0", "0.1", "0.2", "0.25", "0.3", "0.35", "0.4"]

def read_pts(bar, sense):
    from collections import defaultdict
    import re
    pts = defaultdict(list)
    col = {"5": 0, "10": 1, "20": 2}[sense]
    fn = f"{R}/read-nlv-bar{bar}.txt"
    if not os.path.exists(fn):
        return {}
    for line in open(fn):
        m = re.match(r"(mos_\w+)\s+(\d+)C SN\s+([-\d.]+): RBL\s+([-\d.na]+)\s+([-\d.na]+)\s+([-\d.na]+)", line)
        if m:
            pts[(m[1], int(m[2]))].append((float(m[3]), float(m[4 + col])))
    return {k: ns["thresholds"](v) for k, v in pts.items()}

def hold_file(v, b, park):
    names = [f"hold-lv-vlo{v}-bar{b}{'-park' if park else ''}.txt"]
    if v == b:
        names.append(f"hold-lv-vlo{v}{'-park' if park else ''}.txt")
    if park and v == "0":
        names = [f"hold-lv-vlo0.txt"] if b == "0" else []   # VLO 0: park at 0 = opp for a 1
    for n in names:
        if os.path.exists(f"{R}/{n}"):
            return f"{R}/{n}"
    return None

def corner_life(th, res, k, park_zero_file=None):
    l1, h0 = th[k]
    r1, r0 = res.get((k[0], k[1], 1)), res.get((k[0], k[1], 0))
    if not r1 or not r0:
        return None
    t1 = ns["t_at"](r1[0], r1[1], l1, True, r1[2]) if l1 is not None else 0.0
    t0 = ns["t_at"](r0[0], r0[1], h0, False, r0[2]) if h0 is not None else 0.0
    t1 = math.inf if t1 is None else t1
    t0 = math.inf if t0 is None else t0
    return min(t1, t0), t1, t0

def fmt(t):
    if t is None: return "   n/a  "
    if t == math.inf: return "  >50 ms"
    if t == 0: return "  unread"
    return f"{t * 1e3:7.3f}ms" if t >= 1e-3 else f"{t * 1e6:7.2f}us"

out = []
p = lambda s: (out.append(s), print(s))
p("worst-corner lifetime (min over tt/ff/ss x 27/85 C) of a stored 1 and a stored 0; inverter sense")
p("(RBL < 0.5 V reads 1, > 0.7 V reads 0); unread = written level already fails some corner")
for sense in ("10", "20"):
    ths = {b: read_pts(b, sense) for b in BARS}
    for scen in ("opp", "park"):
        p(f"\nsense {sense} ns, WBL {scen}:   rows VLO, columns bar " + "  ".join(f"{b:>8s}" for b in BARS) + "   tracking bar")
        for v in VLOS:
            row, per_corner = [], {}
            for b in BARS:
                f = hold_file(v, b, scen == "park")
                if not f:
                    row.append("      - "); continue
                res, _ = ns["parse_hold"](f)
                lives = {k: corner_life(ths[b], res, k) for k in ths[b]}
                lives = {k: x for k, x in lives.items() if x is not None}
                for k, x in lives.items():
                    per_corner.setdefault(k, []).append((x[0], b))
                row.append(fmt(min(x[0] for x in lives.values())) if lives else "   n/a  ")
            track = ""
            if per_corner:
                best = {k: max(xs) for k, xs in per_corner.items()}
                w = min(best.values())
                track = f"{fmt(w[0])}  (bars " + ", ".join(f"{k[0][4:]}{k[1]}:{b}" for k, (t, b) in sorted(best.items())) + ")"
            p(f"  VLO {v:>4s}   " + "  ".join(row) + "   " + track)
open(f"{R}/matrix.txt", "w").write("\n".join(out) + "\n")
