/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module multiphase_stage(pads, oe, ph3, ph2, ph1, clear, ph0, sub, pin, pin_oe, samples);
  input [1:0] pads;
  wire [1:0] pads;
  input [1:0] oe;
  wire [1:0] oe;
  input ph3;
  wire ph3;
  input ph2;
  wire ph2;
  input ph1;
  wire ph1;
  input clear;
  wire clear;
  input ph0;
  wire ph0;
  input [7:0] sub;
  wire [7:0] sub;
  output [1:0] pin;
  wire [1:0] pin;
  output [1:0] pin_oe;
  wire [1:0] pin_oe;
  output [7:0] samples;
  wire [7:0] samples;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _10;
  wire _110;
  wire _114;
  wire _12;
  wire _120;
  wire _124;
  wire _130;
  wire _134;
  wire _139;
  wire _14;
  wire _144;
  wire _150;
  wire _160;
  wire _170;
  wire _179;
  wire _18;
  wire _24;
  wire _27;
  wire _34;
  wire _37;
  wire _44;
  wire _47;
  wire _54;
  wire _57;
  wire _64;
  wire _67;
  wire _74;
  wire _77;
  wire _84;
  wire _87;
  wire _94;
  wire _97;
  sg13g2_inv_1 _237_ (
    .A(clear),
    .Y(_236_)
  );
  sg13g2_nor2b_1 _238_ (
    .A(clear),
    .B_N(_74),
    .Y(_182_)
  );
  sg13g2_nor2b_1 _239_ (
    .A(clear),
    .B_N(_77),
    .Y(_183_)
  );
  sg13g2_nor2b_1 _240_ (
    .A(clear),
    .B_N(_64),
    .Y(_184_)
  );
  sg13g2_nor2b_1 _241_ (
    .A(clear),
    .B_N(_67),
    .Y(_185_)
  );
  sg13g2_nor2b_1 _242_ (
    .A(clear),
    .B_N(_54),
    .Y(_186_)
  );
  sg13g2_nor2b_1 _243_ (
    .A(clear),
    .B_N(_57),
    .Y(_187_)
  );
  sg13g2_nor2b_1 _244_ (
    .A(clear),
    .B_N(_44),
    .Y(_188_)
  );
  sg13g2_nor2b_1 _245_ (
    .A(clear),
    .B_N(_47),
    .Y(_189_)
  );
  sg13g2_nor2b_1 _246_ (
    .A(clear),
    .B_N(_34),
    .Y(_190_)
  );
  sg13g2_nor2b_1 _247_ (
    .A(clear),
    .B_N(_37),
    .Y(_191_)
  );
  sg13g2_nor2b_1 _248_ (
    .A(clear),
    .B_N(_24),
    .Y(_192_)
  );
  sg13g2_nor2b_1 _249_ (
    .A(clear),
    .B_N(_27),
    .Y(_193_)
  );
  sg13g2_nor2b_1 _250_ (
    .A(clear),
    .B_N(oe[0]),
    .Y(_194_)
  );
  sg13g2_nor2b_1 _251_ (
    .A(clear),
    .B_N(oe[1]),
    .Y(_195_)
  );
  sg13g2_nor2b_1 _252_ (
    .A(clear),
    .B_N(sub[3]),
    .Y(_202_)
  );
  sg13g2_o21ai_1 _253_ (
    .A1(sub[3]),
    .A2(sub[2]),
    .B1(_236_),
    .Y(_216_)
  );
  sg13g2_a21oi_1 _254_ (
    .A1(sub[3]),
    .A2(sub[2]),
    .B1(_216_),
    .Y(_196_)
  );
  sg13g2_o21ai_1 _255_ (
    .A1(_114),
    .A2(_110),
    .B1(_236_),
    .Y(_217_)
  );
  sg13g2_a21oi_1 _256_ (
    .A1(_114),
    .A2(_110),
    .B1(_217_),
    .Y(_197_)
  );
  sg13g2_o21ai_1 _257_ (
    .A1(sub[2]),
    .A2(sub[1]),
    .B1(_236_),
    .Y(_218_)
  );
  sg13g2_a21oi_1 _258_ (
    .A1(sub[2]),
    .A2(sub[1]),
    .B1(_218_),
    .Y(_198_)
  );
  sg13g2_o21ai_1 _259_ (
    .A1(_124),
    .A2(_120),
    .B1(_236_),
    .Y(_219_)
  );
  sg13g2_a21oi_1 _260_ (
    .A1(_124),
    .A2(_120),
    .B1(_219_),
    .Y(_199_)
  );
  sg13g2_o21ai_1 _261_ (
    .A1(sub[1]),
    .A2(sub[0]),
    .B1(_236_),
    .Y(_220_)
  );
  sg13g2_a21oi_1 _262_ (
    .A1(sub[1]),
    .A2(sub[0]),
    .B1(_220_),
    .Y(_200_)
  );
  sg13g2_o21ai_1 _263_ (
    .A1(_134),
    .A2(_130),
    .B1(_236_),
    .Y(_221_)
  );
  sg13g2_a21oi_1 _264_ (
    .A1(_134),
    .A2(_130),
    .B1(_221_),
    .Y(_201_)
  );
  sg13g2_xor2_1 _265_ (
    .A(_139),
    .B(_144),
    .X(_222_)
  );
  sg13g2_o21ai_1 _266_ (
    .A1(sub[0]),
    .A2(_222_),
    .B1(_236_),
    .Y(_223_)
  );
  sg13g2_a21oi_1 _267_ (
    .A1(sub[0]),
    .A2(_222_),
    .B1(_223_),
    .Y(_203_)
  );
  sg13g2_o21ai_1 _268_ (
    .A1(sub[7]),
    .A2(sub[6]),
    .B1(_236_),
    .Y(_224_)
  );
  sg13g2_a21oi_1 _269_ (
    .A1(sub[7]),
    .A2(sub[6]),
    .B1(_224_),
    .Y(_204_)
  );
  sg13g2_o21ai_1 _270_ (
    .A1(_10),
    .A2(_150),
    .B1(_236_),
    .Y(_225_)
  );
  sg13g2_a21oi_1 _271_ (
    .A1(_10),
    .A2(_150),
    .B1(_225_),
    .Y(_205_)
  );
  sg13g2_o21ai_1 _272_ (
    .A1(sub[6]),
    .A2(sub[5]),
    .B1(_236_),
    .Y(_226_)
  );
  sg13g2_a21oi_1 _273_ (
    .A1(sub[6]),
    .A2(sub[5]),
    .B1(_226_),
    .Y(_206_)
  );
  sg13g2_o21ai_1 _274_ (
    .A1(_12),
    .A2(_160),
    .B1(_236_),
    .Y(_227_)
  );
  sg13g2_a21oi_1 _275_ (
    .A1(_12),
    .A2(_160),
    .B1(_227_),
    .Y(_207_)
  );
  sg13g2_o21ai_1 _276_ (
    .A1(sub[5]),
    .A2(sub[4]),
    .B1(_236_),
    .Y(_228_)
  );
  sg13g2_a21oi_1 _277_ (
    .A1(sub[5]),
    .A2(sub[4]),
    .B1(_228_),
    .Y(_208_)
  );
  sg13g2_o21ai_1 _278_ (
    .A1(_14),
    .A2(_170),
    .B1(_236_),
    .Y(_229_)
  );
  sg13g2_a21oi_1 _279_ (
    .A1(_14),
    .A2(_170),
    .B1(_229_),
    .Y(_209_)
  );
  sg13g2_nor2b_1 _280_ (
    .A(clear),
    .B_N(sub[7]),
    .Y(_210_)
  );
  sg13g2_xor2_1 _281_ (
    .A(_179),
    .B(_18),
    .X(_230_)
  );
  sg13g2_o21ai_1 _282_ (
    .A1(sub[4]),
    .A2(_230_),
    .B1(_236_),
    .Y(_231_)
  );
  sg13g2_a21oi_1 _283_ (
    .A1(sub[4]),
    .A2(_230_),
    .B1(_231_),
    .Y(_211_)
  );
  sg13g2_nor2b_1 _284_ (
    .A(clear),
    .B_N(_94),
    .Y(_212_)
  );
  sg13g2_nor2b_1 _285_ (
    .A(clear),
    .B_N(_97),
    .Y(_213_)
  );
  sg13g2_nor2b_1 _286_ (
    .A(clear),
    .B_N(_84),
    .Y(_214_)
  );
  sg13g2_nor2b_1 _287_ (
    .A(clear),
    .B_N(_87),
    .Y(_215_)
  );
  sg13g2_xor2_1 _288_ (
    .A(_134),
    .B(_144),
    .X(_232_)
  );
  sg13g2_xnor2_1 _289_ (
    .A(_114),
    .B(_124),
    .Y(_233_)
  );
  sg13g2_xnor2_1 _290_ (
    .A(_232_),
    .B(_233_),
    .Y(pin[0])
  );
  sg13g2_xor2_1 _291_ (
    .A(_14),
    .B(_18),
    .X(_234_)
  );
  sg13g2_xnor2_1 _292_ (
    .A(_10),
    .B(_12),
    .Y(_235_)
  );
  sg13g2_xnor2_1 _293_ (
    .A(_234_),
    .B(_235_),
    .Y(pin[1])
  );
  sg13g2_nor2b_1 _294_ (
    .A(clear),
    .B_N(pads[1]),
    .Y(_180_)
  );
  sg13g2_nor2b_1 _295_ (
    .A(clear),
    .B_N(pads[0]),
    .Y(_181_)
  );
  sg13g2_dfrbpq_1 _296_ (
    .CLK(ph2),
    .D(_182_),
    .Q(_77),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _297_ (
    .CLK(ph0),
    .D(_183_),
    .Q(samples[2]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _298_ (
    .CLK(ph3),
    .D(_184_),
    .Q(_67),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _299_ (
    .CLK(ph0),
    .D(_185_),
    .Q(samples[3]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _300_ (
    .CLK(ph0),
    .D(_186_),
    .Q(_57),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _301_ (
    .CLK(ph0),
    .D(_187_),
    .Q(samples[4]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _302_ (
    .CLK(ph1),
    .D(_188_),
    .Q(_47),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _303_ (
    .CLK(ph0),
    .D(_189_),
    .Q(samples[5]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _304_ (
    .CLK(ph2),
    .D(_190_),
    .Q(_37),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _305_ (
    .CLK(ph0),
    .D(_191_),
    .Q(samples[6]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _306_ (
    .CLK(ph3),
    .D(_192_),
    .Q(_27),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _307_ (
    .CLK(ph0),
    .D(_193_),
    .Q(samples[7]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _308_ (
    .CLK(ph0),
    .D(_194_),
    .Q(pin_oe[0]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _309_ (
    .CLK(ph0),
    .D(_195_),
    .Q(pin_oe[1]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _310_ (
    .CLK(ph0),
    .D(_196_),
    .Q(_110),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _311_ (
    .CLK(ph3),
    .D(_197_),
    .Q(_114),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _312_ (
    .CLK(ph0),
    .D(_198_),
    .Q(_120),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _313_ (
    .CLK(ph2),
    .D(_199_),
    .Q(_124),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _314_ (
    .CLK(ph0),
    .D(_200_),
    .Q(_130),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _315_ (
    .CLK(ph1),
    .D(_201_),
    .Q(_134),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _316_ (
    .CLK(ph0),
    .D(_202_),
    .Q(_139),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _317_ (
    .CLK(ph0),
    .D(_203_),
    .Q(_144),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _318_ (
    .CLK(ph0),
    .D(_204_),
    .Q(_150),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _319_ (
    .CLK(ph3),
    .D(_205_),
    .Q(_10),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _320_ (
    .CLK(ph0),
    .D(_206_),
    .Q(_160),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _321_ (
    .CLK(ph2),
    .D(_207_),
    .Q(_12),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _322_ (
    .CLK(ph0),
    .D(_208_),
    .Q(_170),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _323_ (
    .CLK(ph1),
    .D(_209_),
    .Q(_14),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _324_ (
    .CLK(ph0),
    .D(_210_),
    .Q(_179),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _325_ (
    .CLK(ph0),
    .D(_211_),
    .Q(_18),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _326_ (
    .CLK(ph0),
    .D(_212_),
    .Q(_97),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _327_ (
    .CLK(ph0),
    .D(_213_),
    .Q(samples[0]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _328_ (
    .CLK(ph1),
    .D(_214_),
    .Q(_87),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _329_ (
    .CLK(ph0),
    .D(_215_),
    .Q(samples[1]),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _330_ (
    .CLK(ph3),
    .D(_180_),
    .Q(_24),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _331_ (
    .CLK(ph2),
    .D(_180_),
    .Q(_34),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _332_ (
    .CLK(ph1),
    .D(_180_),
    .Q(_44),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _333_ (
    .CLK(ph0),
    .D(_180_),
    .Q(_54),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _334_ (
    .CLK(ph3),
    .D(_181_),
    .Q(_64),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _335_ (
    .CLK(ph2),
    .D(_181_),
    .Q(_74),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _336_ (
    .CLK(ph1),
    .D(_181_),
    .Q(_84),
    .RESET_B(1'h1)
  );
  sg13g2_dfrbpq_1 _337_ (
    .CLK(ph0),
    .D(_181_),
    .Q(_94),
    .RESET_B(1'h1)
  );
endmodule
