// Auto-generated by LibreLane
module gc_bank_32x32(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk,
  input rst_n,
  input req,
  input we,
  input[4:0] addr,
  input[31:0] wdata,
  output busy,
  output rvalid,
  output[31:0] rdata,
  output rerr
);
endmodule
