(* Ethernet to TV: raw 10BASE-T frames (EtherType 0x88B5), one source scanline per frame, received
   while NTSC composite video is generated by chasing the beam, both from one 60.852 MHz clock
   (17 x fsc). Two protocols concurrently with a data path between them.

   Capacity split (see README):
     receive  10BASE-T receiver RTL (../ethernet-10base-t, h = 3: Manchester timing + CRC-32, the
              line-code and CRC assists) -> header matcher (pattern/mask compare on the first 14
              bytes: broadcast, EtherType 0x88B5; the systolic matcher's job) -> in-ports 0
              (payload bytes, first 46) and 1 (a status byte at frame end).
     T0       parser: line number -> row select, 32 pixel bytes -> line buffer, 13 pad bytes
              drained, then commit only if the CRC was good. About a quarter of its slots.
     memory   line buffer, K = 4 rows of 32 bytes, gain-cell rows with a lifetime contract.
     T1       video timing: sync/blank on the luma pins by SETP, burst and line playback by
              commands to the pin stage, every edge on an exact slot.
     stage    NCO chroma pins + memory streamer + 16-entry lookup table (video.ml).
     T2, T3   free: here an SPI master loop (pins 4..6) and a UART transmitter loop (pin 7), to show
              isolation.

   Writes the composite waveform (float32 per clock) for the independent decoder (judge_tv.py). *)

let fclk = Video.fclk
let line_slots = 967                     (* 3868 clocks: 227.53 subcarrier cycles *)
let n_lines = 262
let first_active = 21
let src_lines = 120
let active_slot = 172
let field_clocks = 4 * line_slots * n_lines

(* ---------------- T1: video timing ---------------- *)
let luma_all0 = Isa.setp ~mask:0x0F ~value:0 ~oe:1
let sync_on = Isa.setp ~mask:0x04 ~value:0 ~oe:1     (* code 4 -> 0 *)
let sync_off = Isa.setp ~mask:0x04 ~value:1 ~oe:1    (* code 0 -> 4 (blank) *)
let dec_cnt = Isa.shi ~pin:0 ~msb:1                    (* SHI as "decrement cnt": acc is dead here *)

let video_programme ?(extra_slot = false) () =
  let b = Asm.create () in
  let heads = ref [] in
  let stage_cmd t v = [ (t - 1, Asm.W (Isa.lda v)); (t, Asm.W (Isa_mb.send ~ch:7 ~fail:0)) ] in
  (* a group of n identical lines; ev0 is the sync edge at slot 0; slots 1, 2 are reserved for
     LDC and the loop head's JMP; the rest of the events must be at slot >= 3 *)
  let group ?(len = line_slots) name n ev0 events =
    Asm.origin b;
    Asm.at b 0 (Asm.W ev0);
    Asm.at b 1 (Asm.W (Isa.ldc n));
    Asm.at b 2 (Asm.W Isa.nop);
    Asm.label b (name ^ "_rest");
    List.iter (fun (t, w) -> Asm.at b t w) (List.sort compare ((3, Asm.W dec_cnt) :: events));
    Asm.at b (len - 1) (Asm.jnz (name ^ "_head"));
    heads := (name, ev0) :: !heads in
  let burst = stage_cmd 81 Video.cmd_burst_on @ stage_cmd 119 Video.cmd_burst_off in
  let blank_ev = (72, Asm.W sync_off) :: burst in
  let active_ev = blank_ev @ stage_cmd active_slot Video.cmd_active in
  Asm.label b "field";
  group "vs" 3 luma_all0 ([ (412, Asm.W sync_off); (484, Asm.W sync_on); (895, Asm.W sync_off) ] @ stage_cmd 11 Video.cmd_field);
  group "bl" (first_active - 3) sync_on blank_ev;
  group ~len:(if extra_slot then line_slots + 1 else line_slots) "ac" (n_lines - first_active - 1) sync_on active_ev;
  (* bottom line, unrolled, ends with the jump back to the field *)
  Asm.origin b;
  Asm.at b 0 (Asm.W sync_on);
  List.iter (fun (t, w) -> Asm.at b t w) (List.sort compare blank_ev);
  Asm.at b (line_slots - 1) (Asm.jmp "field");
  List.iter (fun (name, ev0) ->
    Asm.label b (name ^ "_head"); Asm.emit b (Asm.W ev0); Asm.emit b (Asm.W Isa.nop); Asm.emit b (Asm.jmp (name ^ "_rest"))) (List.rev !heads);
  let prog, len, _ = Asm.assemble b in
  prog, len

(* ---------------- T0: frame parser ---------------- *)
let parser_programme () =
  let b = Asm.create () in
  let open Asm in
  label b "top";
  block_recv b 4;                               (* line number: wait as long as it takes *)
  block_send b 4;                               (* row select *)
  emit b (W (Isa.ldc 32));
  label b "data";
  emit b (W (Isa.ldd 300)); emit b (recv 4 "abort");
  block_send b 5;
  emit b (W dec_cnt); emit b (jnz "data");
  emit b (W (Isa.ldc 13));
  label b "drain";
  emit b (W (Isa.ldd 300)); emit b (recv 4 "abort");
  emit b (W dec_cnt); emit b (jnz "drain");
  emit b (W (Isa.ldd 3000)); emit b (recv 5 "abort");
  emit b (W (Isa.ldd 0));
  emit b (br_clr 0 "top");                      (* CRC bad: drop, the row stays invalid *)
  block_send b 6;                               (* commit (acc bit 0 = 1) *)
  emit b (jmp "top");
  label b "abort";                              (* runt or stalled frame: resynchronise on its status *)
  block_recv b 5;
  emit b (jmp "top");
  let prog, len, _ = assemble b in
  prog, len

(* ---------------- neighbours on T2, T3 ---------------- *)
let neighbours () =
  let spi = Compiler.spi_master { sclk = 4; mosi = 5; cs = 6; period = 10; sbytes = [ 0xC3 ] } in
  let uart = Compiler.uart_tx { upin = 7; bit_slots = 13; ubytes = [ 0x4F; 0x4B ]; stretch = None } in
  Asm.of_base ~loop:true spi ~plen:128, Asm.of_base ~loop:true uart ~plen:128

(* ---------------- the sender and the wire ---------------- *)
type frame = { t0 : float; edges : float array; bits : int array; t_end : float }

let payload_of_line s =
  (* 8 blocks of 8 pixels: blocks 0, 1 are the line number's nibbles as palette indices (a
     placement check), blocks 2..7 pseudo-random colours *)
  let h = ref (s * 2654435761 land 0xFFFFFF) in
  let rnd () = h := (!h * 1103515245 + 12345) land 0x7FFFFFFF; (!h lsr 16) land 15 in
  let blocks = Array.init 8 (fun bi -> if bi = 0 then s lsr 4 else if bi = 1 then s land 15 else rnd ()) in
  let pix = Array.init 64 (fun k -> blocks.(k / 8)) in
  blocks, List.init 32 (fun i -> (pix.(2 * i) lsl 4) lor pix.((2 * i) + 1))

let frame_bytes ?(ethertype = 0x88B5) ?(corrupt = false) s =
  let _, px = payload_of_line s in
  let payload = [ s ] @ px @ List.init 13 (fun _ -> 0) in
  let f = List.init 6 (fun _ -> 0xFF) @ [ 0x02; 0; 0; 0; 0; 0x01 ] @ Eth_model.be16 ethertype @ payload in
  let fcs = Eth_model.fcs_bytes f in
  let f = if corrupt then List.mapi (fun i x -> if i = 30 then x lxor 0x10 else x) f else f in
  List.init 7 (fun _ -> 0x55) @ [ 0xD5 ] @ f @ fcs

let make_frame ~t0 ~ppm ~jitter bytes =
  let bits = Array.of_list (List.concat_map Eth_model.bits_of_byte bytes) in
  let half = 50e-9 *. (1.0 +. ppm *. 1e-6) in
  let n = 2 * Array.length bits in
  let edges = Array.init (n + 1) (fun k -> t0 +. (float k *. half) +. (if k = 0 || k = n then 0.0 else (Random.float 2.0 -. 1.0) *. jitter)) in
  { t0; edges; bits; t_end = edges.(n) +. (6.0 *. half) }

let frame_level f t =
  if t < f.t0 || t >= f.t_end then 0
  else if t >= f.edges.(Array.length f.edges - 1) then 1
  else begin
    let lo = ref 0 and hi = ref (Array.length f.edges - 1) in
    while !hi - !lo > 1 do let mid = (!lo + !hi) / 2 in if f.edges.(mid) <= t then lo := mid else hi := mid done;
    let k = !lo in
    let b = f.bits.(k / 2) in
    if k mod 2 = 0 then (if b = 1 then -1 else 1) else (if b = 1 then 1 else -1)
  end

(* When display line L's playback starts: T1 executes at cycles 1 + 4k; the stage acts one cycle
   after the SEND. *)
let play_clock line = 1 + (4 * ((line_slots * line) + active_slot)) + 1

type plan = { frames : frame array; sent : (int * [ `Ok | `Corrupt | `Filtered ]) list }

let schedule ?(swap = false) ~seed ~ppm ~jitter () =
  Random.init seed;
  let wire = 72.0 *. 0.8e-6 +. 0.6e-6 in        (* preamble..FCS, TP_IDL *)
  let order = List.init src_lines Fun.id |> List.map (fun s -> if swap && s = 90 then 91 else if swap && s = 91 then 90 else s) in
  let prev_end = ref 0.0 in
  let frames = ref [] and sent = ref [] in
  List.iteri (fun slot s ->
    (* each frame is due by the playback of its first display line, less a random margin; frames
       90 and 91 are sent in swapped order *)
    let due = if swap && slot = 90 then 89 else if swap && slot = 91 then 90 else slot in
    let need = float (play_clock (first_active + (2 * due))) /. fclk in
    let margin = 10e-6 +. Random.float 30e-6 in
    let t0 = Float.max (need -. margin -. wire) (!prev_end +. 9.6e-6) in
    let kind = if s = 40 then `Corrupt else if s = 70 then `Filtered else `Ok in
    let bytes = frame_bytes ~corrupt:(kind = `Corrupt) ~ethertype:(if kind = `Filtered then 0x0800 else 0x88B5) s in
    let f = make_frame ~t0 ~ppm ~jitter bytes in
    prev_end := f.t_end;
    frames := f :: !frames; sent := (s, kind) :: !sent) order;
  { frames = Array.of_list (List.rev !frames); sent = List.rev !sent }

(* header matcher: first 14 bytes against pattern/mask; forwards bytes 14..59 of a match *)
type filt = { mutable idx : int; mutable ok : bool; payload : int Queue.t; status : int Queue.t;
              mutable matched : int; mutable dropped : int; mutable overflow : int; mutable hdr : int list;
              mutable log : (int * int * bool) list (* first payload byte (line), header ok, crc ok *) }
let pattern = Array.of_list (List.init 6 (fun _ -> 0xFF) @ List.init 6 (fun _ -> 0) @ [ 0x88; 0xB5 ])
let pmask = Array.of_list (List.init 6 (fun _ -> 0xFF) @ List.init 6 (fun _ -> 0) @ [ 0xFF; 0xFF ])
let payload_len = 46
let make_filt () = { idx = 0; ok = true; payload = Queue.create (); status = Queue.create (); matched = 0; dropped = 0; overflow = 0;
                     hdr = []; log = [] }
let filt_byte f v =
  if f.idx < 15 then f.hdr <- f.hdr @ [ v ];
  if f.idx < 14 then (if v land pmask.(f.idx) <> pattern.(f.idx) then f.ok <- false)
  else if f.idx < 14 + payload_len && f.ok then (if Queue.length f.payload < 8 then Queue.push v f.payload else f.overflow <- f.overflow + 1);
  f.idx <- f.idx + 1
let filt_end f crc_ok =
  f.log <- ((match List.nth_opt f.hdr 14 with Some l -> l | None -> -1), (if f.ok && f.idx >= 14 then 1 else 0), crc_ok) :: f.log;
  if Sys.getenv_opt "DEBUG" <> None && not (f.ok && f.idx >= 14) then
    Printf.printf "dropped frame: %d bytes, header %s\n" f.idx (String.concat " " (List.map (Printf.sprintf "%02x") f.hdr));
  f.hdr <- [];
  if f.ok && f.idx >= 14 then begin
    f.matched <- f.matched + 1;
    Queue.clear f.payload;
    Queue.push ((if crc_ok then 1 else 0) lor (if f.idx >= 14 + payload_len then 2 else 0)) f.status
  end else f.dropped <- f.dropped + 1;
  f.idx <- 0; f.ok <- true

(* ---------------- the run ---------------- *)
type opts = { tag : string; rtl : bool; video : bool; neigh : [ `Compiled | `Random of int | `None ];
              life_us : float; refresh : bool; extra_slot : bool; out : string option; clocks : int;
              swap : bool; rx_fixed : bool }

let default = { tag = "main"; rtl = true; video = true; neigh = `Compiled; life_us = 120.0; refresh = true;
                extra_slot = false; out = None; clocks = field_clocks + 2000; swap = false; rx_fixed = true }

type result = { comp_hash : int; neigh_hash : int; mism : int; buf : Video.buf; stage : Video.stage; filt : filt;
                sent : (int * [ `Ok | `Corrupt | `Filtered ]) list; wr_bytes : int; commits : int }

let run o =
  let c = Isa_mb.cfg ~pc_bits:7 ~depth:2 () in
  let halt = Array.make 128 Isa.halt in
  let t0p, t1p = if o.video then fst (parser_programme ()), fst (video_programme ~extra_slot:o.extra_slot ()) else halt, halt in
  let t2p, t3p = match o.neigh with
    | `Compiled -> neighbours ()
    | `Random seed -> Random.init seed;
      let p2 = Dual.random_neighbour ~plen:128 ~pins:0x70 ~own:[ 2 ] in
      let p3 = Dual.random_neighbour ~plen:128 ~pins:0x80 ~own:[ 3 ] in p2, p3
    | `None -> halt, halt in
  let mem = [| t0p; t1p; t2p; t3p |] in
  let d = Dual.make ~rtl:o.rtl c mem in
  let plan = if o.video then schedule ~swap:o.swap ~seed:(try int_of_string (Sys.getenv "SEED") with _ -> 7) ~ppm:(try float_of_string (Sys.getenv "PPM") with _ -> -60.0) ~jitter:((try float_of_string (Sys.getenv "JITTER") with _ -> 2.0) *. 1e-9) () else { frames = [||]; sent = [] } in
  let life = int_of_float (o.life_us *. 1e-6 *. fclk) in
  let buf = Video.make_buf ~k:4 ~life ~refresh:o.refresh in
  let stage = Video.make_stage () in
  let filt = make_filt () in
  let rx = Hardcaml.Cyclesim.create (if o.rx_fixed then Eth_rx_fixed.circuit ~h:3 else Eth_rx.circuit ~h:3) in
  let ri n = Hardcaml.Cyclesim.in_port rx n and ro n = Hardcaml.Cyclesim.out_port rx n in
  ri "clear" := Hardcaml.Bits.vdd; Hardcaml.Cyclesim.cycle rx; ri "clear" := Hardcaml.Bits.gnd;
  let oc = Option.map (fun p -> open_out_bin p) o.out in
  let fcur = ref 0 in
  let comp_hash = ref 0 and neigh_hash = ref 0 and wr_bytes = ref 0 in
  let pending = ref [] in
  let fb = Bytes.create 4 in
  for n = 0 to o.clocks - 1 do
    (* the wire and the receiver *)
    let t = float n /. fclk in
    while !fcur < Array.length plan.frames && t >= plan.frames.(!fcur).t_end do incr fcur done;
    let lvl = if !fcur < Array.length plan.frames then frame_level plan.frames.(!fcur) t else 0 in
    ri "rx" := Hardcaml.Bits.of_int ~width:1 (if lvl > 0 then 1 else 0);
    ri "rx_active" := Hardcaml.Bits.of_int ~width:1 (if lvl <> 0 then 1 else 0);
    Hardcaml.Cyclesim.cycle rx;
    let g s = Hardcaml.Bits.to_int !(ro s) in
    (* ports as seen by the core this cycle *)
    let io = { Isa_mb.idle_io with
               pin_in = Dual.pin_out d;
               port_in = [| (if Queue.is_empty filt.payload then 0 else Queue.peek filt.payload);
                            (if Queue.is_empty filt.status then 0 else Queue.peek filt.status); 0; 0 |];
               port_in_valid = [| not (Queue.is_empty filt.payload); not (Queue.is_empty filt.status); false; false |];
               port_out_ready = [| true; true; true; true |] } in
    let e = Dual.step d io in
    (match e.port_pop with Some 0 -> ignore (Queue.pop filt.payload) | Some 1 -> ignore (Queue.pop filt.status) | _ -> ());
    if g "byte_valid" = 1 then filt_byte filt (g "rx_byte");
    if g "frame_end" = 1 then filt_end filt (g "crc_ok" = 1);
    (* the stage and the buffer act on last cycle's pushes (the RTL registers them) *)
    List.iter (fun (p, v) -> match p with
      | 0 -> Video.buf_select buf v
      | 1 -> incr wr_bytes; Video.buf_data buf ~now:n v
      | 2 -> Video.buf_commit buf v
      | _ -> if Sys.getenv_opt "DEBUG" <> None && v = Video.cmd_active && stage.src < 3 then
               Printf.printf "ACTIVE at %d (line %.2f) src %d phase %d tags %s valid %s\n" n (float n /. 3868.) stage.src stage.phase
                 (String.concat "," (Array.to_list (Array.map string_of_int buf.tag))) (String.concat "," (Array.to_list (Array.map string_of_bool buf.valid)));
             if Sys.getenv_opt "DEBUG" <> None && p = 3 && v <> Video.cmd_active && n < 30000 then Printf.printf "cmd %d at %d\n" v n;
             Video.stage_cmd stage ~now:n v) !pending;
    if Sys.getenv_opt "DEBUG" <> None then (match e.port_push with Some (p, v) when p < 3 && n < 200000 -> Printf.printf "port %d <- %d at %d\n" p v n | _ -> ());
    pending := (match e.port_push with Some pv -> [ pv ] | None -> []);
    let po = Dual.pin_out d and oe = Dual.pin_oe d in
    let seq_code = po land oe land 0x0F in
    let code, a, b = Video.stage_clock stage buf ~now:n ~seq_code in
    let v = Video.composite ~code ~a ~b in
    comp_hash := Hashtbl.hash (!comp_hash, code, a, b);
    neigh_hash := Hashtbl.hash (!neigh_hash, (po land 0xF0), (oe land 0xF0));
    (match oc with Some oc -> Bytes.set_int32_le fb 0 (Int32.bits_of_float v); output_bytes oc fb | None -> ())
  done;
  Option.iter close_out oc;
  { comp_hash = !comp_hash; neigh_hash = !neigh_hash; mism = d.mismatches; buf; stage; filt; sent = plan.sent;
    wr_bytes = !wr_bytes; commits = buf.commits }

let write_expect path sent =
  let oc = open_out path in
  let refs = Video.refs () in
  Printf.fprintf oc "# palette reference colours (host prediction), then per source line: kind and 8 block indices\n";
  Array.iteri (fun i (r, g, b) -> Printf.fprintf oc "P %d %.4f %.4f %.4f\n" i r g b) refs;
  List.iter (fun (s, kind) ->
    let blocks, _ = payload_of_line s in
    let k = match kind with `Ok -> "ok" | `Corrupt -> "corrupt" | `Filtered -> "filtered" in
    Printf.fprintf oc "L %d %s %s\n" s k (String.concat " " (Array.to_list (Array.map string_of_int blocks)))) sent;
  Printf.fprintf oc "G play_offset_clocks %d pix_clocks %d fclk %.3f\n" (4 * active_slot) Video.pix_clocks fclk;
  close_out oc

let () =
  let dir = "/var/tmp/multi-proto" in
  let mode = try Sys.argv.(1) with _ -> "all" in
  let t_start = Unix.gettimeofday () in
  let pr = Printf.printf in
  let vp, vl = video_programme () and pp, pl = parser_programme () in
  ignore vp; ignore pp;
  pr "programmes: T0 parser %d words, T1 video timing %d words (of 128)\n" pl vl;
  let pal = Lazy.force Video.palette and refs = Video.refs () in
  pr "palette (luma code, phase, difference, chroma): target -> predicted decode\n";
  Array.iteri (fun i e ->
    let (tr, tg, tb) = Video.targets.(i) and (r, g, b) = refs.(i) in
    pr "  %2d: code %2d th %2d d %2d %s  (%.2f %.2f %.2f) -> (%.2f %.2f %.2f)\n" i e.Video.code e.th e.d (if e.col then "col" else "   ") tr tg tb r g b) pal;
  let mind = ref infinity in
  Array.iteri (fun i a -> Array.iteri (fun j b -> if i < j then mind := Float.min !mind (Video.dist a b)) refs) refs;
  pr "  smallest distance between two palette colours: %.3f\n%!" !mind;
  let report name r =
    pr "%s: RTL/interpreter mismatching cycles %d; frames matched %d, dropped by header %d, commits %d, pixel bytes written %d; \
        lines played %d, underruns %d; buffer reads %d, max write-to-read %.1f us, lifetime violations %d\n%!"
      name r.mism r.filt.matched r.filt.dropped r.commits r.wr_bytes r.stage.lines_played r.stage.underruns r.buf.reads
      (float r.buf.max_interval /. fclk *. 1e6) r.buf.violations in
  if mode = "one" then begin
    let r = run { default with out = Some (dir ^ "/ethtv_main.f32") } in
    report "main (RTL + interpreter, neighbours on T2/T3)" r;
    let seen = List.filter_map (fun (l, h, _) -> if h = 1 then Some l else None) r.filt.log in
    pr "lines not received with a matching header: %s\n" (String.concat " " (List.filter_map (fun (s, _) -> if List.mem s seen then None else Some (string_of_int s)) r.sent));
    write_expect (dir ^ "/ethtv_expect.txt") r.sent
  end;
  if mode = "all" then begin
    let r = run { default with out = Some (dir ^ "/ethtv_main.f32") } in
    report "main (RTL + interpreter, neighbours on T2/T3)" r;
    write_expect (dir ^ "/ethtv_expect.txt") r.sent;
    let rb = run { default with rtl = false; neigh = `None } in
    report "without neighbours" rb;
    pr "isolation: composite trace identical with and without neighbours: %b\n" (rb.comp_hash = r.comp_hash);
    let rn = run { default with rtl = false; video = false } in
    pr "isolation: neighbour pins (4..7) identical with and without Ethernet/video: %b\n" (rn.neigh_hash = r.neigh_hash);
    let same = ref 0 in
    for seed = 1 to 4 do
      let rr = run { default with rtl = false; neigh = `Random seed } in
      if rr.comp_hash = r.comp_hash then incr same
    done;
    pr "isolation: composite identical under 4 random neighbour programme pairs: %d of 4\n%!" !same;
    (* controls *)
    let r8 = run { default with rtl = false; life_us = 8.0; out = Some (dir ^ "/ethtv_life8.f32") } in
    report "control: thin-oxide rows at 85 C (lifetime 8 us)" r8;
    let rn = run { default with rtl = false; refresh = false; out = Some (dir ^ "/ethtv_norefresh.f32") } in
    report "control: no refresh on the first read (lifetime 120 us)" rn;
    let rx = run { default with rtl = false; extra_slot = true; out = Some (dir ^ "/ethtv_extraslot.f32") } in
    report "control: one extra slot in the active line" rx;
    let rs = run { default with rtl = false; rx_fixed = false; out = Some (dir ^ "/ethtv_rxshared.f32") } in
    report "finding: the shared receiver (../ethernet-10base-t/eth_rx.ml, no shift-register clear)" rs;
    let seen = List.filter_map (fun (l, h, _) -> if h = 1 then Some l else None) rs.filt.log in
    pr "  lines not received with a matching header: %s\n" (String.concat " " (List.filter_map (fun (s, _) -> if List.mem s seen then None else Some (string_of_int s)) rs.sent));
    let r1 = run { default with rtl = false; swap = true; out = Some (dir ^ "/ethtv_reorder_thin.f32") } in
    report "reordered pair (91 before 90), thin-oxide rows, 120 us" r1;
    let r2 = run { default with rtl = false; swap = true; life_us = 3000.0; out = Some (dir ^ "/ethtv_reorder_thick.f32") } in
    report "reordered pair (91 before 90), thick-oxide rows, 3 ms" r2
  end;
  pr "elapsed %.0f s\n" (Unix.gettimeofday () -. t_start)

let () =
  if Sys.getenv_opt "DISASM" <> None then begin
    let p, l = video_programme () in
    let dis w = let op = w lsr 12 in
      if op = 14 then Printf.sprintf "%s ch%d fail=%d" (if (w lsr 11) land 1 = 1 then "recv" else "send") ((w lsr 8) land 7) (w land 0x7F)
      else if op = 15 then Printf.sprintf "waitc cond=%d val=%d fail=%d" ((w lsr 7) land 15) ((w lsr 11) land 1) (w land 0x7F)
      else if op = 9 || op = 10 then Printf.sprintf "%s %d" (if op = 9 then "jmp" else "jnz") (w land 0x7F)
      else String.trim (Compiler.disassemble [| w |] 1) in
    Array.iteri (fun i w -> if i < l then Printf.printf "%3d: %s\n" i (dis w)) p;
    exit 0
  end
